const Data = [
  {
    id: 1,
    name: "Gucci Bag",
    size: "M",
    color: "Black",
    star: 5,
    review: "231",
    originlPrice: "300",
    discountedPrice: "299",
    image: "bag.jpg",
  },
  {
    id: 2,
    name: "Marching Cloth",
    size: "L",
    color: "Brown",
    star: 2,
    review: "121",
    originlPrice: "100",
    discountedPrice: "95",
    image: "full.jpg",
  },
  {
    id: 3,
    name: "Shirt",
    size: "XL",
    color: "Red",
    star: 3,
    review: "349",
    originlPrice: "250",
    discountedPrice: "299",
    image: "shirt.jpg",
  },
  {
    id: 4,
    name: "Short",
    size: "L",
    color: "Black",
    star: 6,
    review: "222",
    originlPrice: "90",
    discountedPrice: "90",
    image: "short1.jpg",
  },
  {
    id: 5,
    name: "Short",
    size: "L",
    color: "Differnt",
    star: 4,
    review: "277",
    originlPrice: "90",
    discountedPrice: "90",
    image: "short2.jpg",
  },
  {
    id: 6,
    name: "Sweater",
    size: "XL",
    color: "Black",
    star: 6,
    review: "391",
    originlPrice: "109",
    discountedPrice: "100",
    image: "sweater.jpg",
  },
  {
    id: 7,
    name: "Vest",
    size: "L",
    color: "Brown and white",
    star: 4,
    review: "390",
    originlPrice: "120",
    discountedPrice: "115",
    image: "vest.jpg",
  }
]
export default Data